// This file is auto-generated by @hey-api/openapi-ts

import type { ClientOptions } from 'controller/sdk/types.gen'
import {
    type ClientOptions as DefaultClientOptions,
    type Config,
    createClient,
    createConfig,
} from 'controller/sdk/client'
import { ref, type Ref } from 'vue'
import { assert } from '@vueuse/core';
import { getAuthToken } from './sdk/core/auth.gen';
import { ElDialog, ElMessage, ElNotification } from 'element-plus';
import router from './router';

/**
 * The `createClientConfig()` function will be called on client initialization
 * and the returned object will become the client's initial configuration.
 *
 * You may want to initialize your client this way instead of calling
 * `setConfig()`. This is useful for example if you're using Next.js
 * to ensure your client always has the correct values.
 */
export type CreateClientConfig<T extends DefaultClientOptions = ClientOptions> = (
    override?: Config<DefaultClientOptions & T>,
) => Config<Required<DefaultClientOptions> & T>

export const dataChannel: Ref<RTCDataChannel | null> = ref(null)


const pendingRequests = new Map();



function sendRequest(resource: RequestInfo | URL, options: RequestInit | undefined): Promise<Response> {
    return new Promise((resolve, reject) => {
        // Ensure the channel is actually open
        if (dataChannel.value?.readyState !== 'open') {
            console.warn("WebRTC data channel is not open yet")
            return reject(new Error('WebRTC data channel is not open yet'));
        }

        // Generate a unique ID for correlation
        const requestId = crypto.randomUUID();

        // Set up a timeout so the promise doesn't hang forever
        const timeoutId = setTimeout(() => {
            if (pendingRequests.has(requestId)) {
                pendingRequests.delete(requestId);
                reject(new Error(`Request to ${resource} timed out after ${5000} ms`));
            }
        }, 5000);

        // Save the promise hooks to the registry
        pendingRequests.set(requestId, { resolve, reject, timeoutId });

        const request = new Request(resource, options)

        request.blob().then((value) => {
            value.text().then((text) => {
                // Construct the serialized envelope
                const requestPayload = {
                    id: requestId,
                    type: 'request',
                    path: URL.parse(request.url)?.pathname.replace("/api", ""),
                    method: request.method,
                    body: text,
                };

                // Send via WebRTC
                if (dataChannel.value)
                    dataChannel.value.send(JSON.stringify(requestPayload));
            })

        })
    });
}

export function handleResponse(message) {
    assert(message.type == "response");

    if (pendingRequests.has(message?.id)) {
        const { resolve, timeoutId } = pendingRequests.get(message.id);
        clearTimeout(timeoutId); // Stop the timeout clock
        pendingRequests.delete(message.id); // Clean up registry

        const response = new Response(JSON.stringify(message.body), { status: message.status, headers: { "Content-Type": "application/json" } })

        resolve(response);
    }
}

export const client = createClient(
    createConfig<ClientOptions>({
        baseUrl: window.location.origin + '/api',
        fetch: sendRequest,
    }),
)

export const site_manager_client = createClient(
    createConfig<ClientOptions>({
        baseUrl: window.location.origin + '/api',
        auth: () => localStorage.getItem("auth_token") ?? ""
    })
)

async function myInterceptor(response: Response) {
    const status = response.status

    switch (status) {
        case 401:
            // Handle unauthorized / token expired
            localStorage.removeItem('auth_token')
            ElMessage.error('Session expired. Please log in again.')

            // Bounce them back to login page
            router.push({
                name: 'Login',
                query: { redirect: router.currentRoute.value.fullPath }
            })
            break

        case 403:
            // Handle forbidden access
            ElNotification.error({
                title: 'Access Denied',
                message: 'You do not have permission to view this resource.'
            })
            break

        case 500:
            // Handle server crashes
            ElNotification.error({
                title: 'Server Error',
                message: 'Something went wrong on our end. Please try again later.'
            })
            break

        default:
            // Handle network errors or unhandled status codes
            if (!status) {
                ElMessage.error('Network error. Please check your internet connection.')
            }
            break
    }

    return response
}

site_manager_client.interceptors.response.use(myInterceptor)