#!/bin/sh /etc/rc.common
USE_PROCD=1
START=95
STOP=01
start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "/usr/libexec/controller/inform_wrapper.sh"
    procd_close_instance
}