// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from './client'
import type {
  GetAllDevicesConfigurationDevicesGetData,
  GetAllDevicesConfigurationDevicesGetResponses,
  CreateDeviceConfigurationDevicesPostData,
  CreateDeviceConfigurationDevicesPostResponses,
  CreateDeviceConfigurationDevicesPostErrors,
  GetDeviceConfigurationDevicesDeviceIdGetData,
  GetDeviceConfigurationDevicesDeviceIdGetResponses,
  GetDeviceConfigurationDevicesDeviceIdGetErrors,
  UpdateDeviceConfigurationDevicesDeviceIdPutData,
  UpdateDeviceConfigurationDevicesDeviceIdPutResponses,
  UpdateDeviceConfigurationDevicesDeviceIdPutErrors,
  GetRouterNetjsonConfigConfigurationNetjsonconfigDeviceIdGetData,
  GetRouterNetjsonConfigConfigurationNetjsonconfigDeviceIdGetResponses,
  GetRouterNetjsonConfigConfigurationNetjsonconfigDeviceIdGetErrors,
  GetRouterUciConfigConfigurationUciDeviceIdGetData,
  GetRouterUciConfigConfigurationUciDeviceIdGetResponses,
  GetRouterUciConfigConfigurationUciDeviceIdGetErrors,
  GetRouterRawConfigConfigurationRawDeviceIdGetData,
  GetRouterRawConfigConfigurationRawDeviceIdGetResponses,
  GetRouterRawConfigConfigurationRawDeviceIdGetErrors,
  GetAllNetworksConfigurationNetworksGetData,
  GetAllNetworksConfigurationNetworksGetResponses,
  CreateNetworkConfigurationNetworksPostData,
  CreateNetworkConfigurationNetworksPostResponses,
  CreateNetworkConfigurationNetworksPostErrors,
  GetNetworkConfigurationNetworksNetworkIdGetData,
  GetNetworkConfigurationNetworksNetworkIdGetResponses,
  GetNetworkConfigurationNetworksNetworkIdGetErrors,
  UpdateNetworkConfigurationNetworksNetworkIdPutData,
  UpdateNetworkConfigurationNetworksNetworkIdPutResponses,
  UpdateNetworkConfigurationNetworksNetworkIdPutErrors,
  GetAllWirelessNetworksConfigurationWirelessGetData,
  GetAllWirelessNetworksConfigurationWirelessGetResponses,
  CreateWirelessNetworkConfigurationWirelessPostData,
  CreateWirelessNetworkConfigurationWirelessPostResponses,
  CreateWirelessNetworkConfigurationWirelessPostErrors,
  GetWirelessNetworkConfigurationWirelessWirelessIdGetData,
  GetWirelessNetworkConfigurationWirelessWirelessIdGetResponses,
  GetWirelessNetworkConfigurationWirelessWirelessIdGetErrors,
  UpdateWirelessNetworkConfigurationWirelessWirelessIdPutData,
  UpdateWirelessNetworkConfigurationWirelessWirelessIdPutResponses,
  UpdateWirelessNetworkConfigurationWirelessWirelessIdPutErrors,
  GetAllPortsConfigurationPortsGetData,
  GetAllPortsConfigurationPortsGetResponses,
  CreatePortConfigurationPortsPostData,
  CreatePortConfigurationPortsPostResponses,
  CreatePortConfigurationPortsPostErrors,
  GetPortConfigurationPortsPortIdGetData,
  GetPortConfigurationPortsPortIdGetResponses,
  GetPortConfigurationPortsPortIdGetErrors,
  UpdatePortConfigurationPortsPortIdPutData,
  UpdatePortConfigurationPortsPortIdPutResponses,
  UpdatePortConfigurationPortsPortIdPutErrors,
  RebootControlRebootDeviceIdPostData,
  RebootControlRebootDeviceIdPostResponses,
  RebootControlRebootDeviceIdPostErrors,
  AdoptControlAdoptDeviceIdPostData,
  AdoptControlAdoptDeviceIdPostResponses,
  AdoptControlAdoptDeviceIdPostErrors,
  ProvisionAllControlProvisionPostData,
  ProvisionAllControlProvisionPostResponses,
  UpdateInformControlUpdateInformPostData,
  UpdateInformControlUpdateInformPostResponses,
  ProvisionControlProvisionDeviceIdPostData,
  ProvisionControlProvisionDeviceIdPostResponses,
  ProvisionControlProvisionDeviceIdPostErrors,
  InformControlInformPostData,
  InformControlInformPostResponses,
  InformControlInformPostErrors,
  GetScriptControlScriptNameGetData,
  GetScriptControlScriptNameGetResponses,
  GetScriptControlScriptNameGetErrors,
  GetStatusStatusGetData,
  GetStatusStatusGetResponses,
  GetAllInternetsConfigurationInternetsGetData,
  GetAllInternetsConfigurationInternetsGetResponses,
  CreateInternetConfigurationInternetsPostData,
  CreateInternetConfigurationInternetsPostResponses,
  CreateInternetConfigurationInternetsPostErrors,
  GetInternetConfigurationInternetsDeviceIdPortIdGetData,
  GetInternetConfigurationInternetsDeviceIdPortIdGetResponses,
  GetInternetConfigurationInternetsDeviceIdPortIdGetErrors,
  UpdateInternetConfigurationInternetsDeviceIdPortIdPutData,
  UpdateInternetConfigurationInternetsDeviceIdPortIdPutResponses,
  UpdateInternetConfigurationInternetsDeviceIdPortIdPutErrors,
  NetifyNetifyPostData,
  NetifyNetifyPostResponses,
  GetFlowsNetifyFlowsGetData,
  GetFlowsNetifyFlowsGetResponses,
  GetFlowStatsNetifyFlowsDigestGetData,
  GetFlowStatsNetifyFlowsDigestGetResponses,
  GetFlowStatsNetifyFlowsDigestGetErrors,
  GetActiveFlowsNetifyFlowsActiveGetData,
  GetActiveFlowsNetifyFlowsActiveGetResponses,
  GetLastHourStatsNetifyStatsLastHourGetData,
  GetLastHourStatsNetifyStatsLastHourGetResponses,
  GetHostLastHourStatsNetifyStatsByHostLastDayGetData,
  GetHostLastHourStatsNetifyStatsByHostLastDayGetResponses,
  GetHostLastHourStatsNetifyStatsByHostLastWeekGetData,
  GetHostLastHourStatsNetifyStatsByHostLastWeekGetResponses,
  GetHostLastHourStatsNetifyStatsByHostLastMonthGetData,
  GetHostLastHourStatsNetifyStatsByHostLastMonthGetResponses,
  GetApplicationsMapNetifyApplicationsGetData,
  GetApplicationsMapNetifyApplicationsGetResponses,
} from './types.gen'
import { client } from './client.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Get All Devices
 */
export const getAllDevicesConfigurationDevicesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllDevicesConfigurationDevicesGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAllDevicesConfigurationDevicesGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/configuration/devices/',
    ...options,
  })
}

/**
 * Create Device
 */
export const createDeviceConfigurationDevicesPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateDeviceConfigurationDevicesPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateDeviceConfigurationDevicesPostResponses,
    CreateDeviceConfigurationDevicesPostErrors,
    ThrowOnError
  >({
    url: '/configuration/devices/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Device
 */
export const getDeviceConfigurationDevicesDeviceIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetDeviceConfigurationDevicesDeviceIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetDeviceConfigurationDevicesDeviceIdGetResponses,
    GetDeviceConfigurationDevicesDeviceIdGetErrors,
    ThrowOnError
  >({
    url: '/configuration/devices/{device_id}',
    ...options,
  })
}

/**
 * Update Device
 */
export const updateDeviceConfigurationDevicesDeviceIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateDeviceConfigurationDevicesDeviceIdPutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateDeviceConfigurationDevicesDeviceIdPutResponses,
    UpdateDeviceConfigurationDevicesDeviceIdPutErrors,
    ThrowOnError
  >({
    url: '/configuration/devices/{device_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Router Netjson Config
 */
export const getRouterNetjsonConfigConfigurationNetjsonconfigDeviceIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetRouterNetjsonConfigConfigurationNetjsonconfigDeviceIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetRouterNetjsonConfigConfigurationNetjsonconfigDeviceIdGetResponses,
    GetRouterNetjsonConfigConfigurationNetjsonconfigDeviceIdGetErrors,
    ThrowOnError
  >({
    url: '/configuration/netjsonconfig/{device_id}',
    ...options,
  })
}

/**
 * Get Router Uci Config
 */
export const getRouterUciConfigConfigurationUciDeviceIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetRouterUciConfigConfigurationUciDeviceIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetRouterUciConfigConfigurationUciDeviceIdGetResponses,
    GetRouterUciConfigConfigurationUciDeviceIdGetErrors,
    ThrowOnError
  >({
    url: '/configuration/uci/{device_id}',
    ...options,
  })
}

/**
 * Get Router Raw Config
 */
export const getRouterRawConfigConfigurationRawDeviceIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetRouterRawConfigConfigurationRawDeviceIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetRouterRawConfigConfigurationRawDeviceIdGetResponses,
    GetRouterRawConfigConfigurationRawDeviceIdGetErrors,
    ThrowOnError
  >({
    url: '/configuration/raw/{device_id}',
    ...options,
  })
}

/**
 * Get All Networks
 */
export const getAllNetworksConfigurationNetworksGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllNetworksConfigurationNetworksGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAllNetworksConfigurationNetworksGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/configuration/networks/',
    ...options,
  })
}

/**
 * Create Network
 */
export const createNetworkConfigurationNetworksPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateNetworkConfigurationNetworksPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateNetworkConfigurationNetworksPostResponses,
    CreateNetworkConfigurationNetworksPostErrors,
    ThrowOnError
  >({
    url: '/configuration/networks/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Network
 */
export const getNetworkConfigurationNetworksNetworkIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetNetworkConfigurationNetworksNetworkIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetNetworkConfigurationNetworksNetworkIdGetResponses,
    GetNetworkConfigurationNetworksNetworkIdGetErrors,
    ThrowOnError
  >({
    url: '/configuration/networks/{network_id}',
    ...options,
  })
}

/**
 * Update Network
 */
export const updateNetworkConfigurationNetworksNetworkIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateNetworkConfigurationNetworksNetworkIdPutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateNetworkConfigurationNetworksNetworkIdPutResponses,
    UpdateNetworkConfigurationNetworksNetworkIdPutErrors,
    ThrowOnError
  >({
    url: '/configuration/networks/{network_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get All Wireless Networks
 */
export const getAllWirelessNetworksConfigurationWirelessGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetAllWirelessNetworksConfigurationWirelessGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAllWirelessNetworksConfigurationWirelessGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/configuration/wireless/',
    ...options,
  })
}

/**
 * Create Wireless Network
 */
export const createWirelessNetworkConfigurationWirelessPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateWirelessNetworkConfigurationWirelessPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateWirelessNetworkConfigurationWirelessPostResponses,
    CreateWirelessNetworkConfigurationWirelessPostErrors,
    ThrowOnError
  >({
    url: '/configuration/wireless/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Wireless Network
 */
export const getWirelessNetworkConfigurationWirelessWirelessIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetWirelessNetworkConfigurationWirelessWirelessIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetWirelessNetworkConfigurationWirelessWirelessIdGetResponses,
    GetWirelessNetworkConfigurationWirelessWirelessIdGetErrors,
    ThrowOnError
  >({
    url: '/configuration/wireless/{wireless_id}',
    ...options,
  })
}

/**
 * Update Wireless Network
 */
export const updateWirelessNetworkConfigurationWirelessWirelessIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateWirelessNetworkConfigurationWirelessWirelessIdPutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateWirelessNetworkConfigurationWirelessWirelessIdPutResponses,
    UpdateWirelessNetworkConfigurationWirelessWirelessIdPutErrors,
    ThrowOnError
  >({
    url: '/configuration/wireless/{wireless_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get All Ports
 */
export const getAllPortsConfigurationPortsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllPortsConfigurationPortsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAllPortsConfigurationPortsGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/configuration/ports/',
    ...options,
  })
}

/**
 * Create Port
 */
export const createPortConfigurationPortsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreatePortConfigurationPortsPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreatePortConfigurationPortsPostResponses,
    CreatePortConfigurationPortsPostErrors,
    ThrowOnError
  >({
    url: '/configuration/ports/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Port
 */
export const getPortConfigurationPortsPortIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetPortConfigurationPortsPortIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetPortConfigurationPortsPortIdGetResponses,
    GetPortConfigurationPortsPortIdGetErrors,
    ThrowOnError
  >({
    url: '/configuration/ports/{port_id}',
    ...options,
  })
}

/**
 * Update Port
 */
export const updatePortConfigurationPortsPortIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePortConfigurationPortsPortIdPutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdatePortConfigurationPortsPortIdPutResponses,
    UpdatePortConfigurationPortsPortIdPutErrors,
    ThrowOnError
  >({
    url: '/configuration/ports/{port_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Reboot
 */
export const rebootControlRebootDeviceIdPost = <ThrowOnError extends boolean = false>(
  options: Options<RebootControlRebootDeviceIdPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    RebootControlRebootDeviceIdPostResponses,
    RebootControlRebootDeviceIdPostErrors,
    ThrowOnError
  >({
    url: '/control/reboot/{device_id}',
    ...options,
  })
}

/**
 * Adopt
 */
export const adoptControlAdoptDeviceIdPost = <ThrowOnError extends boolean = false>(
  options: Options<AdoptControlAdoptDeviceIdPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    AdoptControlAdoptDeviceIdPostResponses,
    AdoptControlAdoptDeviceIdPostErrors,
    ThrowOnError
  >({
    url: '/control/adopt/{device_id}',
    ...options,
  })
}

/**
 * Provision All
 */
export const provisionAllControlProvisionPost = <ThrowOnError extends boolean = false>(
  options?: Options<ProvisionAllControlProvisionPostData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ProvisionAllControlProvisionPostResponses,
    unknown,
    ThrowOnError
  >({
    url: '/control/provision',
    ...options,
  })
}

/**
 * Update Inform
 */
export const updateInformControlUpdateInformPost = <ThrowOnError extends boolean = false>(
  options?: Options<UpdateInformControlUpdateInformPostData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    UpdateInformControlUpdateInformPostResponses,
    unknown,
    ThrowOnError
  >({
    url: '/control/update-inform',
    ...options,
  })
}

/**
 * Provision
 */
export const provisionControlProvisionDeviceIdPost = <ThrowOnError extends boolean = false>(
  options: Options<ProvisionControlProvisionDeviceIdPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ProvisionControlProvisionDeviceIdPostResponses,
    ProvisionControlProvisionDeviceIdPostErrors,
    ThrowOnError
  >({
    url: '/control/provision/{device_id}',
    ...options,
  })
}

/**
 * Inform
 */
export const informControlInformPost = <ThrowOnError extends boolean = false>(
  options: Options<InformControlInformPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    InformControlInformPostResponses,
    InformControlInformPostErrors,
    ThrowOnError
  >({
    url: '/control/inform',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Script
 */
export const getScriptControlScriptNameGet = <ThrowOnError extends boolean = false>(
  options: Options<GetScriptControlScriptNameGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetScriptControlScriptNameGetResponses,
    GetScriptControlScriptNameGetErrors,
    ThrowOnError
  >({
    url: '/control/script/{name}',
    ...options,
  })
}

/**
 * Get Status
 */
export const getStatusStatusGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetStatusStatusGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetStatusStatusGetResponses, unknown, ThrowOnError>({
    url: '/status',
    ...options,
  })
}

/**
 * Get All Internets
 */
export const getAllInternetsConfigurationInternetsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllInternetsConfigurationInternetsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetAllInternetsConfigurationInternetsGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/configuration/internets/',
    ...options,
  })
}

/**
 * Create Internet
 */
export const createInternetConfigurationInternetsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateInternetConfigurationInternetsPostData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    CreateInternetConfigurationInternetsPostResponses,
    CreateInternetConfigurationInternetsPostErrors,
    ThrowOnError
  >({
    url: '/configuration/internets/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Get Internet
 */
export const getInternetConfigurationInternetsDeviceIdPortIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetInternetConfigurationInternetsDeviceIdPortIdGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetInternetConfigurationInternetsDeviceIdPortIdGetResponses,
    GetInternetConfigurationInternetsDeviceIdPortIdGetErrors,
    ThrowOnError
  >({
    url: '/configuration/internets/{device_id}/{port_id}',
    ...options,
  })
}

/**
 * Update Internet
 */
export const updateInternetConfigurationInternetsDeviceIdPortIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateInternetConfigurationInternetsDeviceIdPortIdPutData, ThrowOnError>,
) => {
  return (options.client ?? client).put<
    UpdateInternetConfigurationInternetsDeviceIdPortIdPutResponses,
    UpdateInternetConfigurationInternetsDeviceIdPortIdPutErrors,
    ThrowOnError
  >({
    url: '/configuration/internets/{device_id}/{port_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })
}

/**
 * Netify
 */
export const netifyNetifyPost = <ThrowOnError extends boolean = false>(
  options?: Options<NetifyNetifyPostData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<NetifyNetifyPostResponses, unknown, ThrowOnError>({
    url: '/netify/',
    ...options,
  })
}

/**
 * Get Flows
 */
export const getFlowsNetifyFlowsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetFlowsNetifyFlowsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetFlowsNetifyFlowsGetResponses, unknown, ThrowOnError>({
    url: '/netify/flows',
    ...options,
  })
}

/**
 * Get Flow Stats
 */
export const getFlowStatsNetifyFlowsDigestGet = <ThrowOnError extends boolean = false>(
  options: Options<GetFlowStatsNetifyFlowsDigestGetData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    GetFlowStatsNetifyFlowsDigestGetResponses,
    GetFlowStatsNetifyFlowsDigestGetErrors,
    ThrowOnError
  >({
    url: '/netify/flows/{digest}',
    ...options,
  })
}

/**
 * Get Active Flows
 */
export const getActiveFlowsNetifyFlowsActiveGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetActiveFlowsNetifyFlowsActiveGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetActiveFlowsNetifyFlowsActiveGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/netify/flows/active',
    ...options,
  })
}

/**
 * Get Last Hour Stats
 */
export const getLastHourStatsNetifyStatsLastHourGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetLastHourStatsNetifyStatsLastHourGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetLastHourStatsNetifyStatsLastHourGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/netify/stats/last_hour',
    ...options,
  })
}

/**
 * Get Host Last Hour Stats
 */
export const getHostLastHourStatsNetifyStatsByHostLastDayGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetHostLastHourStatsNetifyStatsByHostLastDayGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetHostLastHourStatsNetifyStatsByHostLastDayGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/netify/stats/by_host/last_day',
    ...options,
  })
}

/**
 * Get Host Last Hour Stats
 */
export const getHostLastHourStatsNetifyStatsByHostLastWeekGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetHostLastHourStatsNetifyStatsByHostLastWeekGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetHostLastHourStatsNetifyStatsByHostLastWeekGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/netify/stats/by_host/last_week',
    ...options,
  })
}

/**
 * Get Host Last Hour Stats
 */
export const getHostLastHourStatsNetifyStatsByHostLastMonthGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetHostLastHourStatsNetifyStatsByHostLastMonthGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetHostLastHourStatsNetifyStatsByHostLastMonthGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/netify/stats/by_host/last_month',
    ...options,
  })
}

/**
 * Get Applications Map
 */
export const getApplicationsMapNetifyApplicationsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetApplicationsMapNetifyApplicationsGetData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetApplicationsMapNetifyApplicationsGetResponses,
    unknown,
    ThrowOnError
  >({
    url: '/netify/applications',
    ...options,
  })
}
