// This file is auto-generated by @hey-api/openapi-ts

/**
 * AddressProto
 */
export type AddressProto = 'static' | 'dhcp'

/**
 * AssoclistItem
 */
export type AssoclistItem = {
  /**
   * Mac
   */
  mac: string
}

/**
 * DHCPLease
 */
export type DhcpLease = {
  /**
   * Expires
   */
  expires: number
  /**
   * Hostname
   */
  hostname?: string | null
  /**
   * Macaddr
   */
  macaddr: string
  /**
   * Ipaddr
   */
  ipaddr: string
  /**
   * Duid
   */
  duid?: string | null
  /**
   * Device Id
   */
  device_id: string
}

/**
 * DHCPLeaseBase
 */
export type DhcpLeaseBase = {
  /**
   * Expires
   */
  expires: number
  /**
   * Hostname
   */
  hostname?: string | null
  /**
   * Macaddr
   */
  macaddr: string
  /**
   * Ipaddr
   */
  ipaddr: string
  /**
   * Duid
   */
  duid?: string | null
}

/**
 * Device
 */
export type Device = {
  /**
   * Device Id
   */
  device_id: string
  /**
   * Hostname
   */
  hostname: string
  /**
   * Roles
   */
  roles: Array<DeviceRole>
  address_proto: AddressProto
  /**
   * Address
   */
  address: string | null
  /**
   * Adopted
   */
  adopted: boolean
  /**
   * Model
   */
  model: string | null
}

/**
 * DeviceCommand
 */
export type DeviceCommand = 'noop' | 'adopt' | 'provision' | 'reboot' | 'forget' | 'update-inform'

/**
 * DeviceRole
 */
export type DeviceRole = 'router' | 'ap' | 'switch'

/**
 * DeviceStatusWithDevice
 */
export type DeviceStatusWithDevice = {
  /**
   * Device Id
   */
  device_id: string
  /**
   * Last Inform
   */
  last_inform?: number | null
  /**
   * Last Ip
   */
  last_ip?: string | null
  /**
   * Boot Time
   */
  boot_time?: string | null
  device: Device
  /**
   * Time Since Inform
   */
  time_since_inform: number | null
  /**
   * Up
   */
  readonly up: boolean
  /**
   * Uptime
   */
  readonly uptime: number
}

/**
 * Flow
 */
export type Flow = {
  /**
   * Digest
   */
  digest: string
  /**
   * Application
   */
  application: string
  /**
   * Protocol
   */
  protocol: string
  /**
   * Vlan Id
   */
  vlan_id: number
  /**
   * Active
   */
  active: boolean
  /**
   * First Seen At
   */
  first_seen_at: number
  /**
   * Local Ip
   */
  local_ip: string
  /**
   * Local Port
   */
  local_port: number
  /**
   * Local Mac
   */
  local_mac: string
  /**
   * Other Ip
   */
  other_ip: string
  /**
   * Other Port
   */
  other_port: number
  /**
   * Other Mac
   */
  other_mac: string
}

/**
 * FlowStats
 */
export type FlowStats = {
  /**
   * Digest
   */
  digest: string
  /**
   * Last Seen At
   */
  last_seen_at: number
  /**
   * Local Bytes
   */
  local_bytes: number
  /**
   * Other Bytes
   */
  other_bytes: number
  /**
   * Local Rate
   */
  local_rate: number
  /**
   * Other Rate
   */
  other_rate: number
}

/**
 * FlowWithStats
 */
export type FlowWithStats = {
  /**
   * Digest
   */
  digest: string
  /**
   * Application
   */
  application: string
  /**
   * Protocol
   */
  protocol: string
  /**
   * Vlan Id
   */
  vlan_id: number
  /**
   * Active
   */
  active: boolean
  /**
   * First Seen At
   */
  first_seen_at: number
  /**
   * Local Ip
   */
  local_ip: string
  /**
   * Local Port
   */
  local_port: number
  /**
   * Local Mac
   */
  local_mac: string
  /**
   * Other Ip
   */
  other_ip: string
  /**
   * Other Port
   */
  other_port: number
  /**
   * Other Mac
   */
  other_mac: string
  /**
   * Stats
   */
  stats: Array<FlowStats>
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * InformPayload
 */
export type InformPayload = {
  /**
   * Device Id
   */
  device_id?: string | null
  /**
   * Ip
   */
  ip: string
  /**
   * Boot Time
   */
  boot_time: string
  /**
   * Iwinfo
   */
  iwinfo?: Array<Iwinfo>
  /**
   * Interface Stats
   */
  interface_stats?: {
    [key: string]: InterfaceStats
  } | null
  /**
   * Model
   */
  model?: string | null
  /**
   * Ports
   */
  ports: {
    [key: string]: string
  }
  /**
   * Dhcp Leases
   */
  dhcp_leases: Array<DhcpLeaseBase>
  /**
   * Radios
   */
  radios: {
    [key: string]: {
      [key: string]: unknown
    }
  }
}

/**
 * InformResponse
 */
export type InformResponse = {
  /**
   * Device Id
   */
  device_id?: string
  command?: DeviceCommand
}

/**
 * InterfaceStats
 */
export type InterfaceStats = {
  /**
   * Name
   */
  name: string
}

/**
 * Internet
 */
export type Internet = {
  /**
   * Device Id
   */
  device_id: string
  /**
   * Port Id
   */
  port_id: string
  /**
   * Name
   */
  name: string
}

/**
 * Iwinfo
 */
export type Iwinfo = {
  /**
   * Device
   */
  device: string
  /**
   * Assoclist
   */
  assoclist: Array<AssoclistItem>
}

/**
 * Network
 */
export type NetworkInput = {
  /**
   * Network Id
   */
  network_id: string
  /**
   * Name
   */
  name: string
  /**
   * Gateway Ip
   */
  gateway_ip: string
  /**
   * Subnet Mask
   */
  subnet_mask: number
  /**
   * Management
   */
  management: boolean
  /**
   * Vlan Id
   */
  vlan_id: number
  /**
   * Router Id
   */
  router_id: string | null
  /**
   * Dhcp Server Id
   */
  dhcp_server_id: string | null
  /**
   * Dhcp Start Ip
   */
  dhcp_start_ip: string | null
  /**
   * Dhcp End Ip
   */
  dhcp_end_ip: string | null
}

/**
 * Network
 */
export type NetworkOutput = {
  /**
   * Network Id
   */
  network_id: string
  /**
   * Name
   */
  name: string
  /**
   * Gateway Ip
   */
  gateway_ip: string
  /**
   * Subnet Mask
   */
  subnet_mask: number
  /**
   * Management
   */
  management: boolean
  /**
   * Vlan Id
   */
  vlan_id: number
  /**
   * Router Id
   */
  router_id: string | null
  /**
   * Dhcp Server Id
   */
  dhcp_server_id: string | null
  /**
   * Dhcp Start Ip
   */
  dhcp_start_ip: string | null
  /**
   * Dhcp End Ip
   */
  dhcp_end_ip: string | null
  /**
   * Broadcast Address
   */
  readonly broadcast_address: string
  /**
   * Network Address
   */
  readonly network_address: string
  /**
   * Dhcp Pool Size
   */
  readonly dhcp_pool_size: number
  /**
   * Dhcp Offset
   */
  readonly dhcp_offset: number
}

/**
 * NetworkStatus
 */
export type NetworkStatus = {
  network: NetworkWithDevices
  /**
   * Dhcp Leases
   */
  dhcp_leases?: Array<DhcpLease>
}

/**
 * NetworkWithDevices
 */
export type NetworkWithDevices = {
  /**
   * Network Id
   */
  network_id: string
  /**
   * Name
   */
  name: string
  /**
   * Gateway Ip
   */
  gateway_ip: string
  /**
   * Subnet Mask
   */
  subnet_mask: number
  /**
   * Management
   */
  management: boolean
  /**
   * Vlan Id
   */
  vlan_id: number
  /**
   * Router Id
   */
  router_id: string | null
  /**
   * Dhcp Server Id
   */
  dhcp_server_id: string | null
  /**
   * Dhcp Start Ip
   */
  dhcp_start_ip: string | null
  /**
   * Dhcp End Ip
   */
  dhcp_end_ip: string | null
  router: Device | null
  dhcp_server: Device | null
  /**
   * Broadcast Address
   */
  readonly broadcast_address: string
  /**
   * Network Address
   */
  readonly network_address: string
  /**
   * Dhcp Pool Size
   */
  readonly dhcp_pool_size: number
  /**
   * Dhcp Offset
   */
  readonly dhcp_offset: number
}

/**
 * Port
 */
export type Port = {
  /**
   * Device Id
   */
  device_id: string
  /**
   * Port Id
   */
  port_id: string
  role: PortRole
}

/**
 * PortRole
 */
export type PortRole = 'lan' | 'wan'

/**
 * Status
 */
export type Status = {
  /**
   * Device Status
   */
  device_status?: Array<DeviceStatusWithDevice>
  /**
   * Network Status
   */
  network_status?: Array<NetworkStatus>
}

/**
 * TimeStats
 */
export type TimeStats = {
  /**
   * Flows
   */
  flows: Array<Flow>
  /**
   * Stats
   */
  stats: Array<FlowStats>
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

/**
 * Wireless
 */
export type Wireless = {
  /**
   * Wireless Id
   */
  wireless_id: string
  /**
   * Network Id
   */
  network_id: string
  /**
   * Ssid
   */
  ssid: string
  encryption: WirelessEncryption | null
  /**
   * Key
   */
  key: string | null
}

/**
 * WirelessEncryption
 */
export type WirelessEncryption = 'open' | 'wpa2_personal'

/**
 * DeviceStatusWithDevice
 */
export type DeviceStatusWithDeviceWritable = {
  /**
   * Device Id
   */
  device_id: string
  /**
   * Last Inform
   */
  last_inform?: number | null
  /**
   * Last Ip
   */
  last_ip?: string | null
  /**
   * Boot Time
   */
  boot_time?: string | null
  device: Device
}

/**
 * Network
 */
export type NetworkOutputWritable = {
  /**
   * Network Id
   */
  network_id: string
  /**
   * Name
   */
  name: string
  /**
   * Gateway Ip
   */
  gateway_ip: string
  /**
   * Subnet Mask
   */
  subnet_mask: number
  /**
   * Management
   */
  management: boolean
  /**
   * Vlan Id
   */
  vlan_id: number
  /**
   * Router Id
   */
  router_id: string | null
  /**
   * Dhcp Server Id
   */
  dhcp_server_id: string | null
  /**
   * Dhcp Start Ip
   */
  dhcp_start_ip: string | null
  /**
   * Dhcp End Ip
   */
  dhcp_end_ip: string | null
}

/**
 * NetworkWithDevices
 */
export type NetworkWithDevicesWritable = {
  /**
   * Network Id
   */
  network_id: string
  /**
   * Name
   */
  name: string
  /**
   * Gateway Ip
   */
  gateway_ip: string
  /**
   * Subnet Mask
   */
  subnet_mask: number
  /**
   * Management
   */
  management: boolean
  /**
   * Vlan Id
   */
  vlan_id: number
  /**
   * Router Id
   */
  router_id: string | null
  /**
   * Dhcp Server Id
   */
  dhcp_server_id: string | null
  /**
   * Dhcp Start Ip
   */
  dhcp_start_ip: string | null
  /**
   * Dhcp End Ip
   */
  dhcp_end_ip: string | null
  router: Device | null
  dhcp_server: Device | null
}

export type GetAllDevicesConfigurationDevicesGetData = {
  body?: never
  path?: never
  query?: never
  url: '/configuration/devices/'
}

export type GetAllDevicesConfigurationDevicesGetResponses = {
  /**
   * Response Get All Devices Configuration Devices  Get
   * Successful Response
   */
  200: Array<Device>
}

export type GetAllDevicesConfigurationDevicesGetResponse =
  GetAllDevicesConfigurationDevicesGetResponses[keyof GetAllDevicesConfigurationDevicesGetResponses]

export type CreateDeviceConfigurationDevicesPostData = {
  body: Device
  path?: never
  query?: never
  url: '/configuration/devices/'
}

export type CreateDeviceConfigurationDevicesPostErrors = {
  /**
   * Conflict
   */
  409: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateDeviceConfigurationDevicesPostError =
  CreateDeviceConfigurationDevicesPostErrors[keyof CreateDeviceConfigurationDevicesPostErrors]

export type CreateDeviceConfigurationDevicesPostResponses = {
  /**
   * Successful Response
   */
  201: Device
}

export type CreateDeviceConfigurationDevicesPostResponse =
  CreateDeviceConfigurationDevicesPostResponses[keyof CreateDeviceConfigurationDevicesPostResponses]

export type GetDeviceConfigurationDevicesDeviceIdGetData = {
  body?: never
  path: {
    /**
     * Device Id
     */
    device_id: string
  }
  query?: never
  url: '/configuration/devices/{device_id}'
}

export type GetDeviceConfigurationDevicesDeviceIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetDeviceConfigurationDevicesDeviceIdGetError =
  GetDeviceConfigurationDevicesDeviceIdGetErrors[keyof GetDeviceConfigurationDevicesDeviceIdGetErrors]

export type GetDeviceConfigurationDevicesDeviceIdGetResponses = {
  /**
   * Successful Response
   */
  200: Device
}

export type GetDeviceConfigurationDevicesDeviceIdGetResponse =
  GetDeviceConfigurationDevicesDeviceIdGetResponses[keyof GetDeviceConfigurationDevicesDeviceIdGetResponses]

export type UpdateDeviceConfigurationDevicesDeviceIdPutData = {
  body: Device
  path: {
    /**
     * Device Id
     */
    device_id: string
  }
  query?: never
  url: '/configuration/devices/{device_id}'
}

export type UpdateDeviceConfigurationDevicesDeviceIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateDeviceConfigurationDevicesDeviceIdPutError =
  UpdateDeviceConfigurationDevicesDeviceIdPutErrors[keyof UpdateDeviceConfigurationDevicesDeviceIdPutErrors]

export type UpdateDeviceConfigurationDevicesDeviceIdPutResponses = {
  /**
   * Successful Response
   */
  200: Device
}

export type UpdateDeviceConfigurationDevicesDeviceIdPutResponse =
  UpdateDeviceConfigurationDevicesDeviceIdPutResponses[keyof UpdateDeviceConfigurationDevicesDeviceIdPutResponses]

export type GetRouterNetjsonConfigConfigurationNetjsonconfigDeviceIdGetData = {
  body?: never
  path: {
    /**
     * Device Id
     */
    device_id: string
  }
  query?: never
  url: '/configuration/netjsonconfig/{device_id}'
}

export type GetRouterNetjsonConfigConfigurationNetjsonconfigDeviceIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetRouterNetjsonConfigConfigurationNetjsonconfigDeviceIdGetError =
  GetRouterNetjsonConfigConfigurationNetjsonconfigDeviceIdGetErrors[keyof GetRouterNetjsonConfigConfigurationNetjsonconfigDeviceIdGetErrors]

export type GetRouterNetjsonConfigConfigurationNetjsonconfigDeviceIdGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetRouterUciConfigConfigurationUciDeviceIdGetData = {
  body?: never
  path: {
    /**
     * Device Id
     */
    device_id: string
  }
  query?: never
  url: '/configuration/uci/{device_id}'
}

export type GetRouterUciConfigConfigurationUciDeviceIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetRouterUciConfigConfigurationUciDeviceIdGetError =
  GetRouterUciConfigConfigurationUciDeviceIdGetErrors[keyof GetRouterUciConfigConfigurationUciDeviceIdGetErrors]

export type GetRouterUciConfigConfigurationUciDeviceIdGetResponses = {
  /**
   * Successful Response
   */
  200: string
}

export type GetRouterUciConfigConfigurationUciDeviceIdGetResponse =
  GetRouterUciConfigConfigurationUciDeviceIdGetResponses[keyof GetRouterUciConfigConfigurationUciDeviceIdGetResponses]

export type GetRouterRawConfigConfigurationRawDeviceIdGetData = {
  body?: never
  path: {
    /**
     * Device Id
     */
    device_id: string
  }
  query?: never
  url: '/configuration/raw/{device_id}'
}

export type GetRouterRawConfigConfigurationRawDeviceIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetRouterRawConfigConfigurationRawDeviceIdGetError =
  GetRouterRawConfigConfigurationRawDeviceIdGetErrors[keyof GetRouterRawConfigConfigurationRawDeviceIdGetErrors]

export type GetRouterRawConfigConfigurationRawDeviceIdGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetAllNetworksConfigurationNetworksGetData = {
  body?: never
  path?: never
  query?: never
  url: '/configuration/networks/'
}

export type GetAllNetworksConfigurationNetworksGetResponses = {
  /**
   * Response Get All Networks Configuration Networks  Get
   * Successful Response
   */
  200: Array<NetworkWithDevices>
}

export type GetAllNetworksConfigurationNetworksGetResponse =
  GetAllNetworksConfigurationNetworksGetResponses[keyof GetAllNetworksConfigurationNetworksGetResponses]

export type CreateNetworkConfigurationNetworksPostData = {
  body: NetworkInput
  path?: never
  query?: never
  url: '/configuration/networks/'
}

export type CreateNetworkConfigurationNetworksPostErrors = {
  /**
   * Conflict
   */
  409: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateNetworkConfigurationNetworksPostError =
  CreateNetworkConfigurationNetworksPostErrors[keyof CreateNetworkConfigurationNetworksPostErrors]

export type CreateNetworkConfigurationNetworksPostResponses = {
  /**
   * Successful Response
   */
  201: NetworkOutput
}

export type CreateNetworkConfigurationNetworksPostResponse =
  CreateNetworkConfigurationNetworksPostResponses[keyof CreateNetworkConfigurationNetworksPostResponses]

export type GetNetworkConfigurationNetworksNetworkIdGetData = {
  body?: never
  path: {
    /**
     * Network Id
     */
    network_id: unknown
  }
  query?: never
  url: '/configuration/networks/{network_id}'
}

export type GetNetworkConfigurationNetworksNetworkIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetNetworkConfigurationNetworksNetworkIdGetError =
  GetNetworkConfigurationNetworksNetworkIdGetErrors[keyof GetNetworkConfigurationNetworksNetworkIdGetErrors]

export type GetNetworkConfigurationNetworksNetworkIdGetResponses = {
  /**
   * Successful Response
   */
  200: NetworkWithDevices
}

export type GetNetworkConfigurationNetworksNetworkIdGetResponse =
  GetNetworkConfigurationNetworksNetworkIdGetResponses[keyof GetNetworkConfigurationNetworksNetworkIdGetResponses]

export type UpdateNetworkConfigurationNetworksNetworkIdPutData = {
  body: NetworkInput
  path: {
    /**
     * Network Id
     */
    network_id: string
  }
  query?: never
  url: '/configuration/networks/{network_id}'
}

export type UpdateNetworkConfigurationNetworksNetworkIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateNetworkConfigurationNetworksNetworkIdPutError =
  UpdateNetworkConfigurationNetworksNetworkIdPutErrors[keyof UpdateNetworkConfigurationNetworksNetworkIdPutErrors]

export type UpdateNetworkConfigurationNetworksNetworkIdPutResponses = {
  /**
   * Successful Response
   */
  200: NetworkOutput
}

export type UpdateNetworkConfigurationNetworksNetworkIdPutResponse =
  UpdateNetworkConfigurationNetworksNetworkIdPutResponses[keyof UpdateNetworkConfigurationNetworksNetworkIdPutResponses]

export type GetAllWirelessNetworksConfigurationWirelessGetData = {
  body?: never
  path?: never
  query?: never
  url: '/configuration/wireless/'
}

export type GetAllWirelessNetworksConfigurationWirelessGetResponses = {
  /**
   * Response Get All Wireless Networks Configuration Wireless  Get
   * Successful Response
   */
  200: Array<Wireless>
}

export type GetAllWirelessNetworksConfigurationWirelessGetResponse =
  GetAllWirelessNetworksConfigurationWirelessGetResponses[keyof GetAllWirelessNetworksConfigurationWirelessGetResponses]

export type CreateWirelessNetworkConfigurationWirelessPostData = {
  body: Wireless
  path?: never
  query?: never
  url: '/configuration/wireless/'
}

export type CreateWirelessNetworkConfigurationWirelessPostErrors = {
  /**
   * Conflict
   */
  409: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateWirelessNetworkConfigurationWirelessPostError =
  CreateWirelessNetworkConfigurationWirelessPostErrors[keyof CreateWirelessNetworkConfigurationWirelessPostErrors]

export type CreateWirelessNetworkConfigurationWirelessPostResponses = {
  /**
   * Successful Response
   */
  201: Wireless
}

export type CreateWirelessNetworkConfigurationWirelessPostResponse =
  CreateWirelessNetworkConfigurationWirelessPostResponses[keyof CreateWirelessNetworkConfigurationWirelessPostResponses]

export type GetWirelessNetworkConfigurationWirelessWirelessIdGetData = {
  body?: never
  path: {
    /**
     * Wireless Id
     */
    wireless_id: unknown
  }
  query?: never
  url: '/configuration/wireless/{wireless_id}'
}

export type GetWirelessNetworkConfigurationWirelessWirelessIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetWirelessNetworkConfigurationWirelessWirelessIdGetError =
  GetWirelessNetworkConfigurationWirelessWirelessIdGetErrors[keyof GetWirelessNetworkConfigurationWirelessWirelessIdGetErrors]

export type GetWirelessNetworkConfigurationWirelessWirelessIdGetResponses = {
  /**
   * Successful Response
   */
  200: Wireless
}

export type GetWirelessNetworkConfigurationWirelessWirelessIdGetResponse =
  GetWirelessNetworkConfigurationWirelessWirelessIdGetResponses[keyof GetWirelessNetworkConfigurationWirelessWirelessIdGetResponses]

export type UpdateWirelessNetworkConfigurationWirelessWirelessIdPutData = {
  body: Wireless
  path: {
    /**
     * Wireless Id
     */
    wireless_id: string
  }
  query?: never
  url: '/configuration/wireless/{wireless_id}'
}

export type UpdateWirelessNetworkConfigurationWirelessWirelessIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateWirelessNetworkConfigurationWirelessWirelessIdPutError =
  UpdateWirelessNetworkConfigurationWirelessWirelessIdPutErrors[keyof UpdateWirelessNetworkConfigurationWirelessWirelessIdPutErrors]

export type UpdateWirelessNetworkConfigurationWirelessWirelessIdPutResponses = {
  /**
   * Successful Response
   */
  200: Wireless
}

export type UpdateWirelessNetworkConfigurationWirelessWirelessIdPutResponse =
  UpdateWirelessNetworkConfigurationWirelessWirelessIdPutResponses[keyof UpdateWirelessNetworkConfigurationWirelessWirelessIdPutResponses]

export type GetAllPortsConfigurationPortsGetData = {
  body?: never
  path?: never
  query?: never
  url: '/configuration/ports/'
}

export type GetAllPortsConfigurationPortsGetResponses = {
  /**
   * Response Get All Ports Configuration Ports  Get
   * Successful Response
   */
  200: Array<Port>
}

export type GetAllPortsConfigurationPortsGetResponse =
  GetAllPortsConfigurationPortsGetResponses[keyof GetAllPortsConfigurationPortsGetResponses]

export type CreatePortConfigurationPortsPostData = {
  body: Port
  path?: never
  query?: never
  url: '/configuration/ports/'
}

export type CreatePortConfigurationPortsPostErrors = {
  /**
   * Conflict
   */
  409: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreatePortConfigurationPortsPostError =
  CreatePortConfigurationPortsPostErrors[keyof CreatePortConfigurationPortsPostErrors]

export type CreatePortConfigurationPortsPostResponses = {
  /**
   * Successful Response
   */
  201: Port
}

export type CreatePortConfigurationPortsPostResponse =
  CreatePortConfigurationPortsPostResponses[keyof CreatePortConfigurationPortsPostResponses]

export type GetPortConfigurationPortsPortIdGetData = {
  body?: never
  path: {
    /**
     * Port Id
     */
    port_id: unknown
  }
  query?: never
  url: '/configuration/ports/{port_id}'
}

export type GetPortConfigurationPortsPortIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetPortConfigurationPortsPortIdGetError =
  GetPortConfigurationPortsPortIdGetErrors[keyof GetPortConfigurationPortsPortIdGetErrors]

export type GetPortConfigurationPortsPortIdGetResponses = {
  /**
   * Successful Response
   */
  200: Port
}

export type GetPortConfigurationPortsPortIdGetResponse =
  GetPortConfigurationPortsPortIdGetResponses[keyof GetPortConfigurationPortsPortIdGetResponses]

export type UpdatePortConfigurationPortsPortIdPutData = {
  body: Port
  path: {
    /**
     * Port Id
     */
    port_id: number
  }
  query?: never
  url: '/configuration/ports/{port_id}'
}

export type UpdatePortConfigurationPortsPortIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdatePortConfigurationPortsPortIdPutError =
  UpdatePortConfigurationPortsPortIdPutErrors[keyof UpdatePortConfigurationPortsPortIdPutErrors]

export type UpdatePortConfigurationPortsPortIdPutResponses = {
  /**
   * Successful Response
   */
  200: Port
}

export type UpdatePortConfigurationPortsPortIdPutResponse =
  UpdatePortConfigurationPortsPortIdPutResponses[keyof UpdatePortConfigurationPortsPortIdPutResponses]

export type RebootControlRebootDeviceIdPostData = {
  body?: never
  path: {
    /**
     * Device Id
     */
    device_id: string
  }
  query?: never
  url: '/control/reboot/{device_id}'
}

export type RebootControlRebootDeviceIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type RebootControlRebootDeviceIdPostError =
  RebootControlRebootDeviceIdPostErrors[keyof RebootControlRebootDeviceIdPostErrors]

export type RebootControlRebootDeviceIdPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type AdoptControlAdoptDeviceIdPostData = {
  body?: never
  path: {
    /**
     * Device Id
     */
    device_id: string
  }
  query?: never
  url: '/control/adopt/{device_id}'
}

export type AdoptControlAdoptDeviceIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type AdoptControlAdoptDeviceIdPostError =
  AdoptControlAdoptDeviceIdPostErrors[keyof AdoptControlAdoptDeviceIdPostErrors]

export type AdoptControlAdoptDeviceIdPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type ProvisionAllControlProvisionPostData = {
  body?: never
  path?: never
  query?: never
  url: '/control/provision'
}

export type ProvisionAllControlProvisionPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type UpdateInformControlUpdateInformPostData = {
  body?: never
  path?: never
  query?: never
  url: '/control/update-inform'
}

export type UpdateInformControlUpdateInformPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type ProvisionControlProvisionDeviceIdPostData = {
  body?: never
  path: {
    /**
     * Device Id
     */
    device_id: string
  }
  query?: never
  url: '/control/provision/{device_id}'
}

export type ProvisionControlProvisionDeviceIdPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ProvisionControlProvisionDeviceIdPostError =
  ProvisionControlProvisionDeviceIdPostErrors[keyof ProvisionControlProvisionDeviceIdPostErrors]

export type ProvisionControlProvisionDeviceIdPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type InformControlInformPostData = {
  body: InformPayload
  path?: never
  query?: never
  url: '/control/inform'
}

export type InformControlInformPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type InformControlInformPostError =
  InformControlInformPostErrors[keyof InformControlInformPostErrors]

export type InformControlInformPostResponses = {
  /**
   * Successful Response
   */
  200: InformResponse
}

export type InformControlInformPostResponse =
  InformControlInformPostResponses[keyof InformControlInformPostResponses]

export type GetScriptControlScriptNameGetData = {
  body?: never
  path: {
    /**
     * Name
     */
    name: string
  }
  query?: never
  url: '/control/script/{name}'
}

export type GetScriptControlScriptNameGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetScriptControlScriptNameGetError =
  GetScriptControlScriptNameGetErrors[keyof GetScriptControlScriptNameGetErrors]

export type GetScriptControlScriptNameGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetStatusStatusGetData = {
  body?: never
  path?: never
  query?: never
  url: '/status'
}

export type GetStatusStatusGetResponses = {
  /**
   * Successful Response
   */
  200: Status
}

export type GetStatusStatusGetResponse =
  GetStatusStatusGetResponses[keyof GetStatusStatusGetResponses]

export type GetAllInternetsConfigurationInternetsGetData = {
  body?: never
  path?: never
  query?: never
  url: '/configuration/internets/'
}

export type GetAllInternetsConfigurationInternetsGetResponses = {
  /**
   * Response Get All Internets Configuration Internets  Get
   * Successful Response
   */
  200: Array<Internet>
}

export type GetAllInternetsConfigurationInternetsGetResponse =
  GetAllInternetsConfigurationInternetsGetResponses[keyof GetAllInternetsConfigurationInternetsGetResponses]

export type CreateInternetConfigurationInternetsPostData = {
  body: Internet
  path?: never
  query?: never
  url: '/configuration/internets/'
}

export type CreateInternetConfigurationInternetsPostErrors = {
  /**
   * Conflict
   */
  409: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type CreateInternetConfigurationInternetsPostError =
  CreateInternetConfigurationInternetsPostErrors[keyof CreateInternetConfigurationInternetsPostErrors]

export type CreateInternetConfigurationInternetsPostResponses = {
  /**
   * Successful Response
   */
  201: Internet
}

export type CreateInternetConfigurationInternetsPostResponse =
  CreateInternetConfigurationInternetsPostResponses[keyof CreateInternetConfigurationInternetsPostResponses]

export type GetInternetConfigurationInternetsDeviceIdPortIdGetData = {
  body?: never
  path: {
    /**
     * Device Id
     */
    device_id: string
    /**
     * Port Id
     */
    port_id: string
  }
  query?: never
  url: '/configuration/internets/{device_id}/{port_id}'
}

export type GetInternetConfigurationInternetsDeviceIdPortIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetInternetConfigurationInternetsDeviceIdPortIdGetError =
  GetInternetConfigurationInternetsDeviceIdPortIdGetErrors[keyof GetInternetConfigurationInternetsDeviceIdPortIdGetErrors]

export type GetInternetConfigurationInternetsDeviceIdPortIdGetResponses = {
  /**
   * Successful Response
   */
  200: Internet
}

export type GetInternetConfigurationInternetsDeviceIdPortIdGetResponse =
  GetInternetConfigurationInternetsDeviceIdPortIdGetResponses[keyof GetInternetConfigurationInternetsDeviceIdPortIdGetResponses]

export type UpdateInternetConfigurationInternetsDeviceIdPortIdPutData = {
  body: Internet
  path: {
    /**
     * Device Id
     */
    device_id: string
    /**
     * Port Id
     */
    port_id: string
  }
  query?: never
  url: '/configuration/internets/{device_id}/{port_id}'
}

export type UpdateInternetConfigurationInternetsDeviceIdPortIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type UpdateInternetConfigurationInternetsDeviceIdPortIdPutError =
  UpdateInternetConfigurationInternetsDeviceIdPortIdPutErrors[keyof UpdateInternetConfigurationInternetsDeviceIdPortIdPutErrors]

export type UpdateInternetConfigurationInternetsDeviceIdPortIdPutResponses = {
  /**
   * Successful Response
   */
  200: Internet
}

export type UpdateInternetConfigurationInternetsDeviceIdPortIdPutResponse =
  UpdateInternetConfigurationInternetsDeviceIdPortIdPutResponses[keyof UpdateInternetConfigurationInternetsDeviceIdPortIdPutResponses]

export type NetifyNetifyPostData = {
  body?: never
  path?: never
  query?: never
  url: '/netify/'
}

export type NetifyNetifyPostResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetFlowsNetifyFlowsGetData = {
  body?: never
  path?: never
  query?: never
  url: '/netify/flows'
}

export type GetFlowsNetifyFlowsGetResponses = {
  /**
   * Response Get Flows Netify Flows Get
   * Successful Response
   */
  200: Array<Flow>
}

export type GetFlowsNetifyFlowsGetResponse =
  GetFlowsNetifyFlowsGetResponses[keyof GetFlowsNetifyFlowsGetResponses]

export type GetFlowStatsNetifyFlowsDigestGetData = {
  body?: never
  path: {
    /**
     * Digest
     */
    digest: string
  }
  query?: never
  url: '/netify/flows/{digest}'
}

export type GetFlowStatsNetifyFlowsDigestGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetFlowStatsNetifyFlowsDigestGetError =
  GetFlowStatsNetifyFlowsDigestGetErrors[keyof GetFlowStatsNetifyFlowsDigestGetErrors]

export type GetFlowStatsNetifyFlowsDigestGetResponses = {
  /**
   * Successful Response
   */
  200: FlowWithStats
}

export type GetFlowStatsNetifyFlowsDigestGetResponse =
  GetFlowStatsNetifyFlowsDigestGetResponses[keyof GetFlowStatsNetifyFlowsDigestGetResponses]

export type GetActiveFlowsNetifyFlowsActiveGetData = {
  body?: never
  path?: never
  query?: never
  url: '/netify/flows/active'
}

export type GetActiveFlowsNetifyFlowsActiveGetResponses = {
  /**
   * Response Get Active Flows Netify Flows Active Get
   * Successful Response
   */
  200: Array<Flow>
}

export type GetActiveFlowsNetifyFlowsActiveGetResponse =
  GetActiveFlowsNetifyFlowsActiveGetResponses[keyof GetActiveFlowsNetifyFlowsActiveGetResponses]

export type GetLastHourStatsNetifyStatsLastHourGetData = {
  body?: never
  path?: never
  query?: never
  url: '/netify/stats/last_hour'
}

export type GetLastHourStatsNetifyStatsLastHourGetResponses = {
  /**
   * Successful Response
   */
  200: TimeStats
}

export type GetLastHourStatsNetifyStatsLastHourGetResponse =
  GetLastHourStatsNetifyStatsLastHourGetResponses[keyof GetLastHourStatsNetifyStatsLastHourGetResponses]

export type GetHostLastHourStatsNetifyStatsByHostLastDayGetData = {
  body?: never
  path?: never
  query?: never
  url: '/netify/stats/by_host/last_day'
}

export type GetHostLastHourStatsNetifyStatsByHostLastDayGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetHostLastHourStatsNetifyStatsByHostLastWeekGetData = {
  body?: never
  path?: never
  query?: never
  url: '/netify/stats/by_host/last_week'
}

export type GetHostLastHourStatsNetifyStatsByHostLastWeekGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetHostLastHourStatsNetifyStatsByHostLastMonthGetData = {
  body?: never
  path?: never
  query?: never
  url: '/netify/stats/by_host/last_month'
}

export type GetHostLastHourStatsNetifyStatsByHostLastMonthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetApplicationsMapNetifyApplicationsGetData = {
  body?: never
  path?: never
  query?: never
  url: '/netify/applications'
}

export type GetApplicationsMapNetifyApplicationsGetResponses = {
  /**
   * Response Get Applications Map Netify Applications Get
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type GetApplicationsMapNetifyApplicationsGetResponse =
  GetApplicationsMapNetifyApplicationsGetResponses[keyof GetApplicationsMapNetifyApplicationsGetResponses]

export type ClientOptions = {
  baseUrl: 'http://localhost:8000' | (string & {})
}
